//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int TaskId { get; set; }
        public int CustomerID { get; set; }
        public int UserID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime DeadlineTime { get; set; }
        public bool isFinised { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual User User { get; set; }
    }
}
